tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    command: |
      pip3 install httpie 
      mkdir ~gitpod/.config/httpie
      cp .config/httpie/config.json ~gitpod/.config/httpie
      gp open intro.md
     

  # --------------------------------------
  - name: working-terminal
    openMode: split-right

ports:
  - port: 9011
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 9012
    onOpen: ignore
    visibility: public
  - port: 9020
    onOpen: ignore
    visibility: public
  - port: 9021
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public

vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix
